---
title: "【React18 新機能】React18の動作確認（Suspense編）"
emoji: "⛳"
type: "tech" # tech: 技術記事 / idea: アイデア
topics: ["React", "javascript"]
published: false
---

# はじめに

今回は React18 の新機能`Suspense`について確認していきたいと思います。
Transition と Automatic Batchig ついてはこちらの記事をご覧ください。
https://zenn.dev/rh820/articles/686701ba31ed44
https://zenn.dev/rh820/articles/3403e2b1533f6c

### 動作確認用リポジトリ

https://github.com/dahoho/react-18-demo

# Suspense とは？

> サスペンスにより、コンポーネントツリーの一部がまだ表示できない場合に、ロード中という状態を宣言的に記述できるようになります：

```tsx
<Suspense fallback={<Spinner />}>
  <Comments />
</Suspense>
```

> サスペンスにより、「UI ロード中状態」というものが、React のプログラミングモデルで宣言的に記述可能な主要コンセプトに昇格します。その上により高レベルな機能を構築していけるようになります。
> 我々は数年前に機能限定版のサスペンスを導入しました。しかしサポートされているユースケースは React.lazy によるコード分割のみであり、サーバでのレンダーにおいては一切サポートされていませんでした。
> React 18 ではサーバ側でのサスペンスのサポートを追加し、並行レンダリング機能を用いてその能力を向上させました。
> React 18 におけるサスペンスはトランジション API と併用した場合に能力を発揮します。トランジション中でサスペンドが発生すると、React は既に見えているコンテンツがフォールバックによって隠されてしまわないようにするのです。代わりに、十分なデータがロードされるまでレンダーを遅らせて、望ましくないロード中状態が見えないようにします。

(引用元：[https://ja.legacy.reactjs.org/blog/2022/03/29/react-v18.html#new-suspense-features](https://ja.legacy.reactjs.org/blog/2022/03/29/react-v18.html#new-suspense-features))

Suspense は、コンポーネントツリーの一部がまだ表示できない場合に、ロード中という状態を宣言的に記述できるようになります。

## Suspense を使用したコンポーネントの動作確認

実際に動作確認をしてみます。

### ローディングの表示

axios と ReactQuery を使用して、jsonplaceholder からデータを取得して表示するコンポーネントで動作確認をしたいと思います。

まず、axios と ReactQuery をインストールして、index.tsx で QueryClient と QueryClientProvider をインポートします。
queryClient に共通の設定を追加します。
`suspense: true`を追加して、ReactQuery のクエリに関してはすべて Suspense を有効化しています。

```tsx:index.tsx
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./components/App";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      suspense: true,
    },
  },
});

const root = ReactDOM.createRoot(
  document.getElementById("root") as HTMLElement
);
root.render(
  <QueryClientProvider client={queryClient}>
    <App />
  </QueryClientProvider>
);
```

以下のコンポーネントでは、`useQuery`を使用して、jsonplaceholder からデータを取得しています。
今回は、このコンポーネントが表示されるまでの間にローディングを表示したいと思います。

```tsx:ReactQuery.tsx
import { useQuery } from "@tanstack/react-query";
import axios from "axios";

type Comments = {
  postId: number;
  id: number;
  name: string;
  email: string;
  body: string;
};

const fetchComments = async () => {
  const res = await axios.get<Comments[]>(
    "https://jsonplaceholder.typicode.com/comments"
  );
  return res.data;
};

const ReactQuery = () => {
  const { data } = useQuery<Comments[]>(
    ["comments"],
    fetchComments
  );

  return (
    <div>
      <ul className="grid gap-5 mt-8">
        {data?.map((comment) => (
          <li key={comment.id}>
            <p className="font-bold">{comment.name}</p>
            <p className="mt-2">{comment.body}</p>
            <p className="mt-2">{comment.email}</p>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default ReactQuery;


```

先ほどのコンポーネントを`App.tsx`で呼び出します。
react から`Suspense`をインポートし、`<Suspense>`タグで囲みます。
`<Suspense>`タグの中には、`fallback`というプロパティを指定することができ、ローディング中に表示するコンポーネントを指定することができます。
今回は、ローディング中と表示することにします。

```tsx:App.tsx
import SuspenseTest from "./SuspenseTest/SuspenseTest";
import { Suspense } from "react";

const App = () => {
return (
  <main className="py-16 px-5">
    <Suspense fallback={<p className="text-center">ローディング中</p>}>
      <SuspenseTest />
    </Suspense>
  </main>
);
};

export default App;
```

## 動作確認

:::message
動作確認がしやすいように Chrome のデベロッパーツールで回線速度を`Fast 3G`に設定しています。
:::
![](https://storage.googleapis.com/zenn-user-upload/a1e97673e057-20230923.png)

Suspense を使用して、ローディング中のテキストが表示されていることが確認できました。
![](https://storage.googleapis.com/zenn-user-upload/6b9c972b0495-20230923.gif)

### エラーハンドリング

Suspense を使用して、エラーハンドリングを行うには、`ErrorBoundary`が必要になります。
先ほどの Suspense では、`ErrorBoundary`を使用していないので、エラーが発生した場合には、エラーが表示されません。
`ErrorBoundary` はエラーが発生した場合に、エラーをキャッチして、エラーを表示するコンポーネントです。
インストール後に、`ErrorBoundary`をインポートして以下のように`<Suspense>`を囲って、fallback にエラー時に表示するコンポーネントを指定します。

```tsx:App.tsx
import SuspenseTest from "./SuspenseTest/SuspenseTest";
import { Suspense } from "react";
import { ErrorBoundary } from "react-error-boundary";

const App = () => {
  return (
    <main className="py-16 px-5">
      <ErrorBoundary fallback={<p>エラーが発生しました。</p>}>
        <Suspense fallback={<p className="text-center">ローディング中</p>}>
          <SuspenseTest />
        </Suspense>
      </ErrorBoundary>
    </main>
  );
};

export default App;
```

## 動作確認

エンドポイントを変更して、エラーが発生するようにして確認したところ、
エラーメッセージを表示することができました。
![](https://storage.googleapis.com/zenn-user-upload/f5b012de9f58-20230923.png)

## 複数の Suspense の組み合わせ
